# Generated by Django 5.0 on 2023-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=100)),
                ('date_blog', models.DateTimeField(auto_now=True)),
                ('description_blog', models.CharField(max_length=250)),
                ('url_blog', models.URLField(blank=True)),
            ],
        ),
    ]
