# Generated by Django 5.0 on 2023-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_project',
            name='description_blog',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog_project',
            name='title_blog',
            field=models.CharField(max_length=200),
        ),
    ]
